#pragma once

#define IOFTPD_VERSION_MAJOR 7
#define IOFTPD_VERSION_MINOR 10
#define IOFTPD_VERSION_PATCH 0
#define IOFTPD_VERSION_BUILD 0

// String helpers
#define STRINGIFY2(x) #x
#define STRINGIFY(x) STRINGIFY2(x)

#define IOFTPD_VERSION_STRING \
    STRINGIFY(IOFTPD_VERSION_MAJOR) "." \
    STRINGIFY(IOFTPD_VERSION_MINOR) "." \
    STRINGIFY(IOFTPD_VERSION_PATCH) "." \
    STRINGIFY(IOFTPD_VERSION_BUILD)
