# generate_version.ps1 — writes include/GitVersion.h from current git state.
#
# Called as a pre-build Target in ioFTPD-v7.vcxproj:
#   powershell.exe -NoProfile -ExecutionPolicy Bypass
#     -File "$(ProjectDir)scripts\generate_version.ps1" "$(ProjectDir)"
#
# If git is unavailable (e.g. source downloaded as a zip), a fallback header
# is written so the build still succeeds.  The output file is gitignored;
# never commit it.
#
# Output: include/GitVersion.h
#   IOFTPD_GIT_HASH         — 7-char abbreviated commit hash, or "unknown"
#   IOFTPD_GIT_DIRTY        — 1 if working tree has uncommitted changes, else 0
#   IOFTPD_GIT_COMMIT_COUNT — total commit count from root to HEAD (monotonically
#                             increasing on a single branch; used as the BUILD
#                             component of FILEVERSION so builds are numerically
#                             comparable)
#   IOFTPD_GIT_SUFFIX       — pre-computed version suffix string:
#                             "-abcdef0"        (clean build)
#                             "-abcdef0-dirty"  (uncommitted changes present)
#                             "-unknown"        (git unavailable)
#
# The content is only rewritten when it changes so that MSVC's incremental
# build is not invalidated on every build when nothing has changed in git.

param([string]$ProjectDir = $PSScriptRoot + "\..")

$ErrorActionPreference = "Continue"

$hash   = "unknown"
$count  = 0
$dirty  = $false
$suffix = "-unknown"

try {
    $h = git -C $ProjectDir rev-parse --short=7 HEAD 2>$null
    if ($LASTEXITCODE -eq 0 -and $h) {
        $hash = $h.Trim()

        $n = git -C $ProjectDir rev-list --count HEAD 2>$null
        if ($LASTEXITCODE -eq 0 -and $n) {
            $count = [int]($n.Trim())
        }

        $s = git -C $ProjectDir status --porcelain 2>$null
        $dirty = ($LASTEXITCODE -eq 0) -and ($s -ne $null) -and ($s.Trim() -ne "")

        $suffix = if ($dirty) { "-$hash-dirty" } else { "-$hash" }
    }
} catch {
    # git not on PATH or repo not initialised — use fallback values set above
}

$dirtyInt = if ($dirty) { 1 } else { 0 }

$content = @"
/* Auto-generated by scripts/generate_version.ps1 — DO NOT EDIT, DO NOT COMMIT.
 * See .gitignore.  Regenerated automatically before each build.
 * hash=$hash  count=$count  dirty=$dirtyInt */
#pragma once

#define IOFTPD_GIT_HASH         "$hash"
#define IOFTPD_GIT_DIRTY        $dirtyInt
#define IOFTPD_GIT_COMMIT_COUNT $count
#define IOFTPD_GIT_SUFFIX       "$suffix"
"@

$outputFile = Join-Path $ProjectDir "include\GitVersion.h"

# Only rewrite when content differs — avoids invalidating the incremental build.
# Use WriteAllBytes with explicit UTF-8 no-BOM to prevent MSVC C2054 on the
# first line (Windows PowerShell 5.1 adds a BOM when using Set-Content -Encoding UTF8).
$utf8NoBom = New-Object System.Text.UTF8Encoding $false
$newBytes  = $utf8NoBom.GetBytes($content + "`n")

$rewrite = $true
if (Test-Path $outputFile) {
    try {
        $existingBytes = [System.IO.File]::ReadAllBytes($outputFile)
        if ([System.Linq.Enumerable]::SequenceEqual(
                [byte[]]$existingBytes, [byte[]]$newBytes)) {
            $rewrite = $false
        }
    } catch { }
}

if ($rewrite) {
    [System.IO.File]::WriteAllBytes($outputFile, $newBytes)
    Write-Host "generate_version.ps1: wrote $outputFile (hash=$hash count=$count dirty=$dirtyInt)"
} else {
    Write-Host "generate_version.ps1: $outputFile is up to date"
}
